# Gunakan Python versi ringan
FROM python:3.14-slim

# Set working directory di container
WORKDIR /app

# Copy semua file project ke container
COPY . .

# Jalankan program utama
CMD ["python", "main.py"]
