# Gunakan Python versi ringan
FROM python:3.14-alpine

# Set direktori kerja di container
WORKDIR /app

# Salin semua file dari folder code ke container
COPY . /app

# Jalankan program utama
CMD ["python", "main.py"]
